### ISSUE TITLE
Add support for passing json object rather than a json file.

### ISSUE THREAD

**Issue by sahijs** [glouwa/d3-hypertree#25]
**Is your feature request related to a problem? Please describe.**
There is a need to render the tree based on an APi call that returns a json object.

**Describe the solution you'd like**
It would we nice to add fromData to the loaders.  And the inputs would be json payload like such.
function loadData(ok, data) {
	var t0, dl;
	t0 = performance.now();
    dl = data.length;
    ok(data, t0, dl);
}
exports.fromData = f => ok => loadData(ok, f);

**Describe alternatives you've considered**
None yet.

**Additional context**
I am willing to contribute.

**Comment by glouwa** [comment]
I also think such a function would be convenient. It is possible to pass a lambda expression for this use case, like in the [minimal-inlinedata example](https://github.com/glouwa/d3-hypertree-examples/blob/master/examples-html/minimal-inlinedata/index.html), but i think **your solution is cleaner**. If you want you can make a pull request, otherwise i will add it if you want.

You are welcome to contribute, what are your interests? 
Regarding workflows i added a [CONTRIBUTING.md](https://github.com/glouwa/d3-hypertree/blob/master/CONTRIBUTING.md) file to the project, containing a how to contribute.

I also look forward for any other feedback.

**Comment by glouwa** [comment]
in master

**Comment by glouwa** [comment]
in master

**Comment by sahijs** [comment]
Thanks for making this change.  I got involved in other projects therefore had not had the time to look deeper.  Now I have little time and wanted to get back to this.  Do you have any examples of hypertree working in a webpack.  I have an existing angular app where I am trying to import this and render.  I am not having any luck.  if you could point me to a example, that would be great.

**Comment by glouwa** [comment]
i have a gulpfile using webpack, does this help?

[gulp-webpack.zip](https://github.com/glouwa/d3-hypertree/files/3163751/gulp-webpack.zip)

**Comment by sahijs** [comment]
Thanks, I was able to use the slides example and get the hypertree to show up within angular app.

I am now trying to figure out if there is a way to set the color of the links (arc) to be data driven.

Regards,
Jesse

**Comment by glouwa** [comment]
if i got it right, you want to set the color links individually, right? this is not possible yet. you can set color of the links by css, but all links will have the same color.

**Comment by glouwa** [comment]
hi, now links and node color can be set in a data driven way. see new examples.
